### ISSUE TITLE
(Suggestion) More detailed errors?

### ISSUE THREAD

**Issue by zOwenn** [davqvist/Restriction#3]
Just as an idea, a quality of life addition i guess, would it be possible to point out where an issue is in the error message that pops up when not in a closed room? Like, possibly at what point in the search/ what block coordinate is the problem - and if the search ended because the room is too large? 

Not a definite requirement, but would be nice for the situations where it is difficult to find what is causing the room to not be sealed :)

**Comment by davqvist** [comment]
There is no functional difference between a room being too large or a hole in a room. I can't detect that. At some point I have to stop looking for the room border. I could write in the error message the block that is furtest away from the machine that is "in the room" maybe but not sure if it would more confuse than help.

**Comment by zOwenn** [comment]
Yeah, okay - I should have looked at the code and seen that before making the suggestion :) Apologies

**Comment by Mr-Wallet** [comment]
I wonder if something couldn't be done for spaces where non-air clearly surrounds the area. Perhaps a hint of a block type it encountered which is not considered "closing"? I googled this repo to read the source because it seems like the easiest way to figure out why my 5x5x3 room isn't considered closed.

**Comment by davqvist** [comment]
Again, how can I detect where the open spot is? How I can I showcase this? Let me try. 

Let's assume you have a very big house with 2 big rooms. Between the rooms you have an open door or a 2 high walkway. The machine is saying the room is not closed but that is because the rooms are too big and go over the cap (because I have to stop at sometime searching for a closed room if it indeed isn't closed). What error message should I describe? "Room is too big" is what you want, but another house which is slightly smaller but has a hole or an open door wants me to tell the coords of the hole/open door. How can I tell the difference? I just stopped looking after a certain amount of blocks if it is closed, I could have found the hole early and searched the whole time outside for a closed room. Not sure how, but let's say I find "holes", then I would false alarm the small walkway in the house with the 2 rooms as hole, because technically it is one, but an intentional one. 

I hope it is clear now. I can't possibly detect the position of the hole as the house can be of whatever shape.

**Comment by Mr-Wallet** [comment]
What I meant was that if the only hole(s) is not an Air block, and can detect a space which _is_ closed off _if_ you only considered Air to be open, then I'd be very interested in an ordered list of the non-air blocks it passed through before it failed, in breadth-first order. Once all of my room decorations are ruled out, the first block in the list is very likely to be relevant to why my room isn't working.

If that's not feasible then even just a generic hint about what constitutes a non-solid block would help people a lot.
